version: "3.7"

services:
        frontend:
                container_name: react
                build: 
                        context: .
                        dockerfile: Dockerfile
                volumes:
                        - ".:/app"
                        - "/app/node_modules"
                ports:
                        - "80:8080"
                environment:
                        - NODE_ENV=development                        
